[package]
name = "racking"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = {version = "0.4.45", features = ["serde"] }
serde = "1.0.229"
serde_derive = "1.0.229"
serde_json = "1.0.151"

[build-dependencies]
blake3 = "1.8.7"

[dev-dependencies]
tokio = { version = "1", features = ["tokio-macros", "macros", "rt", "fs", "rt-multi-thread"] }
reqwest = {version = "0.12", features = ["json", "blocking"]}
